routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();
Route::prefix('programas')->group(function () {
    Route::resource('periodos', 'PeriodoController');
    Route::resource('gestions', 'GestionController');
    Route::resource('programas', 'ProgramaController');
    Route::get('programas/{id}/modulo', 'ProgramaController@programaModulo')->name('programa_modulo');
    Route::resource('modulos', 'ModuloController');
    Route::resource('ofertas', 'OfertaController');
    Route::resource('categorias', 'CategoriaController');
});

Route::prefix('reservaInscripcion')->group(function () {
    Route::resource('reservas', 'ReservaController');
    Route::put('reserva/{id}/anular','ReservaController@anularReserva')->name('reserva.anular');
    Route::put('reserva/{id}/inscribir','ReservaController@inscribirReserva')->name('reserva.inscribir');

    Route::resource('inscripcions', 'InscripcionController');
    Route::get('inscripcions/{id}/materias', 'InscripcionController@materia')->name('inscripcion.materia'); // necesita el id inscripcion
    Route::post('inscripcions/{id}/materias/calificar', 'InscripcionController@calificar')->name('inscripcion.calificar'); // necesita el id inscripcion

    Route::get('pagar/Inscripcion/{id}', 'PagoController@realizarPagoInscripcion')->name('pagar.inscripcion'); // necesita el id inscripcion
    Route::put('pago/Inscripcion/{id}', 'PagoController@confirmarPagoInscripcion')->name('pagar.inscripcion.post');


    Route::resource('pagos', 'PagoController');

    Route::get('pagar/reserva/{id}', 'PagoController@realizarPagoReserva')->name('pagar.reserva'); // necesita el id de la reserva
    Route::put('pago/reserva/{id}', 'PagoController@confirmarPago')->name('pagar.reserva.post');
    //Route::get('pagar/Inscripcion/{id}', 'PagoController@realizarPagoInscripcion')->name('pagar.inscripcion'); // necesita el id de la reserva

    Route::get('pagar/SaladoInscripcion/{id}', 'PagoController@realizarPagoSaldoInscripcion')->name('pagar.saldo.inscripcion'); // necesita el id inscripcion
    Route::put('pagar/SaladoInscripcion/{id}', 'PagoController@confirmarPagoSaldoInscripcion')->name('pagar.saldo.post'); // necesita el id inscripcion



});


Route::prefix('administradorUsuario')->group(function () {
    Route::resource('users', 'UserController');
    Route::resource('profesors', 'ProfesorController');
    Route::resource('estudiantes', 'EstudianteController');
    Route::resource('administrativos', 'AdministrativoController');

    Route::resource('personas', 'PersonaController');


    Route::post('roles/store', 'RoleController@store')->name('roles.store')
        ->middleware('can:permission:roles.create');

    Route::get('roles', 'RoleController@index')->name('roles.index')
        ->middleware('can:permission:roles.index');

    Route::get('roles/create', 'RoleController@create')->name('roles.create')
        ->middleware('can:permission:roles.create');

    Route::PATCH('roles/{role}', 'RoleController@update')->name('roles.update')
        ->middleware('can:permission:roles.edit');

    Route::get('roles/{role}', 'RoleController@show')->name('roles.show')
        ->middleware('can:permission:roles.show');

    Route::delete('roles/{role}', 'RoleController@destroy')->name('roles.destroy')
        ->middleware('can:permission:roles.destroy');

    Route::get('roles/{role}/edit', 'RoleController@edit')->name('roles.edit')
        ->middleware('can:permission:roles.edit');

});

Route::prefix('reportes')->group(function () {
    Route::get('reporte_bi', 'ReporteController@reporte_bi')->name('reporte.reporte_bi');


    Route::get('alumnos_reprobados', 'ReporteController@alumnos_reprobados')->name('reporte.alumnos_reprobados');
    Route::get('PDF_alumnos_reprobados', 'ReporteController@PDF_alumnos_reprobados')->name('reporte.PDF_alumnos_reprobados');
    Route::get('estudiantes_deudores', 'ReporteController@estudiantes_deudores')->name('reporte.estudiantes_deudores');
    Route::get('PDF_estudiantes_deudores', 'ReporteController@PDF_estudiantes_deudores')->name('reporte.PDF_estudiantes_deudores');
    Route::get('lista_profesores_materia', 'ReporteController@lista_profesores_materia')->name('reporte.lista_profesores_materia');
    Route::get('PDF_lista_profesores_materia', 'ReporteController@PDF_lista_profesores_materia')->name('reporte.PDF_lista_profesores_materia');
    Route::get('recaudacion_por_modulo', 'ReporteController@recaudacion_por_modulo')->name('reporte.recaudacion_por_modulo');
    Route::get('PDF_recaudacion_por_modulo', 'ReporteController@PDF_recaudacion_por_modulo')->name('reporte.PDF_recaudacion_por_modulo');
    Route::get('cantidad_alumnos_modulo', 'ReporteController@cantidad_alumnos_modulo')->name('reporte.cantidad_alumnos_modulo');
    Route::get('PDF_cantidad_alumnos_modulo', 'ReporteController@PDF_cantidad_alumnos_modulo')->name('reporte.PDF_cantidad_alumnos_modulo');


    Route::get('alumnos_pendientes_en_inscripcion', 'ReporteController@alumnos_pendientes_en_inscripcion')->name('reporte.alumnos_pendientes_en_inscripcion');
    Route::get('PDF_alumnos_pendientes_en_inscripcion', 'ReporteController@PDF_alumnos_pendientes_en_inscripcion')->name('reporte.PDF_alumnos_pendientes_en_inscripcion');

});









Route::prefix('Reporte')->group(function () {
   /// Route::get('ordenPdf/{id}', 'OrdenController@exportarPdf')->name('reporte.ordenPdf');
});



Route::get('/home', 'HomeController@index')->name('home');


//Route::get('agenda', 'AgendaController@index');


/////  busqueda
Route::post('/search', 'HomeController@search')->name('search');

///// estilos

Route::get('/estilos', 'HomeController@estilosCreate')->name('estilos.index');
Route::get('/estilos/{id}/create', 'HomeController@estilosStoreTemplete')->name('estilos.store.templete');
Route::post('/estilos/font', 'HomeController@estilosStoregeFont')->name('estilos.store.font');
Route::get('/estilos/restablecer', 'HomeController@estilosRestablecer')->name('estilos.restablecer');

/// visitas

Route::post('/visitas', 'HomeController@vistaStore')->name('visita.store');



Route::resource('agendas', 'AgendaController');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

app/Models/Inscripcion.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Inscripcion",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="fecha",
 *          description="fecha",
 *          type="string",
 *          format="date"
 *      ),
 *      @SWG\Property(
 *          property="user_id",
 *          description="user_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="estudiante_id",
 *          description="estudiante_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Inscripcion extends Model
{
    use SoftDeletes;

    public $table = 'inscripcion';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'fecha',
        'user_id',
        'estudiante_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'fecha' => 'date',
        'user_id' => 'integer',
        'estudiante_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
    //    'monto' => 'required',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function User()
    {
        return $this->belongsTo(\App\Models\User::class,  'user_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function Estudiante()
    {
        return $this->belongsTo(\App\Models\Estudiante::class,  'estudiante_id');
    }

    public function modulos()
    {
        return $this->belongsToMany(\App\Models\Modulo::class, 'inscripcion_modulo', 'inscripcion_id', 'modulo_id')->withPivot('calificaciones','id');
    }

}

app/Http/Controllers/InscripcionController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Validator;

use App\Http\Requests\CreateInscripcionRequest;
use App\Http\Requests\UpdateInscripcionRequest;
use App\Models\Categoria;
use App\Models\Estudiante;
use App\Models\Inscripcion;
use App\Models\Modulo;
use App\Models\Reserva;
use App\Repositories\InscripcionRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Support\Facades\Auth;
use Response;
use DB;
class InscripcionController extends AppBaseController
{
    /** @var  InscripcionRepository */
    private $inscripcionRepository;

    public function __construct(InscripcionRepository $inscripcionRepo)
    {
        $this->inscripcionRepository = $inscripcionRepo;
    }

    /**
     * Display a listing of the Inscripcion.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $codigo=$request->get('codigo');
        $user=$request->get('user');
        $estudiante=$request->get('estudiante');
        $now = new \DateTime();

        $fecha = DB::table('inscripcion')
            ->orderBy('fecha', 'asc')
            ->first();
        $fecha=array($fecha->fecha ,$now->format('Y-m-d H:i:s'));
        if($request->get('fecha')) {

            $fecha = explode("to", $request->get('fecha'));
            $inscripciones =Inscripcion::orderBy('inscripcion.id', 'DESC')
                ->join('users', 'users.id', '=', 'inscripcion.user_id')
                ->join('estudiantes', 'estudiantes.id', '=', 'inscripcion.estudiante_id')
                ->join('personas', 'personas.id', '=', 'estudiantes.persona_id')
                ->where('personas.nombre','LIKE',"%$estudiante%")
                ->where('users.email','LIKE',"%$user%")
                ->where('inscripcion.id','LIKE',"%$codigo%")
                ->whereBetween('inscripcion.fecha',[$fecha[0],$fecha[1]])
                ->select('inscripcion.*')
                ->paginate(10)->setPath ( '' );

        }else{

            $inscripciones=Inscripcion::orderBy('inscripcion.id', 'DESC')
                ->join('users', 'users.id', '=', 'inscripcion.user_id')
                ->join('estudiantes', 'estudiantes.id', '=', 'inscripcion.estudiante_id')
                ->join('personas', 'personas.id', '=', 'estudiantes.persona_id')
                ->where('personas.nombre','LIKE',"%$estudiante%")
                //->orWhere('personas.apellido_paterno','LIKE',"%$estudiante%")
               // ->orWhere('personas.apellido_materno','LIKE',"%$estudiante%")
                ->where('users.email','LIKE',"%$user%")
                ->where('inscripcion.id','LIKE',"%$codigo%")
                ->select('inscripcion.*')
                ->paginate(10)->setPath ( '' );

        }

        $pagination = $inscripciones->appends ( array (
            'codigo' => $request->get( 'codigo' ),
            'estudiante' => $request->get( 'estudiante' ),
            'user' => $request->get( 'user' ),
            'fecha' => $request->get( 'fecha' )
        ) );

        return view('inscripcions.index',compact('inscripciones','codigo','user','estudiante','fecha'));
          //  ->with('inscripcions', $inscripciones);
    }





    public function materia($id)
    {
        $inscripcion=Inscripcion::find($id);


        return view('inscripcions.materias', compact('inscripcion'));
    }





    public function calificar(Request $request,$id)
    {
        $calificacion=$request->input('calificacion');;

        $v = Validator::make($request->all(), [
            'calificacion' => 'required|numeric|min:0|max:100',
        ]);
        if($v->fails())
        {
            Flash::warning('Ingrese un numero de un rango de 0 a 100.');

            return redirect()->back()->withErrors($v)->withInput();
        }

        DB::table('inscripcion_modulo')
            ->where('id', $id)
            ->update(['calificaciones' => $calificacion]);

        return  redirect()->back();
    }

    public function create()
    {
        $estudiantes=Estudiante::all();
        $categoria=Categoria::all();

        return view('inscripcions.create', compact('estudiantes','categoria'));
    }

    /**
     * Store a newly created Inscripcion in storage.
     *
     * @param CreateInscripcionRequest $request
     *
     * @return Response
     */

    public function store(CreateInscripcionRequest $request)
    {
        $input = $request->all();


        $inscripcion= new Inscripcion();
        $now = new \DateTime();
        $inscripcion->fecha=$now->format('Y-m-d H:i:s');
        $inscripcion->user_id=Auth::id();
        $inscripcion->estudiante_id=$request->input('estudiante_id');;
        $inscripcion->save();

        $inscripcion->modulos()->sync($request->get('modulos_id'));

      //  $inscripcion = $this->inscripcionRepository->create($input);


        Flash::success('Inscripcion saved successfully.');

        return redirect(route('pagar.inscripcion', $inscripcion->id));//create.pagos


      //  return redirect(route('inscripcions.index'));
    }

    /**
     * Display the specified Inscripcion.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $inscripcion = $this->inscripcionRepository->find($id);

        if (empty($inscripcion)) {
            Flash::error('Inscripcion not found');

            return redirect(route('inscripcions.index'));
        }

        return view('inscripcions.show')->with('inscripcion', $inscripcion);
    }

    /**
     * Show the form for editing the specified Inscripcion.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $inscripcion = $this->inscripcionRepository->find($id);

        if (empty($inscripcion)) {
            Flash::error('Inscripcion not found');

            return redirect(route('inscripcions.index'));
        }

        return view('inscripcions.edit')->with('inscripcion', $inscripcion);
    }

    /**
     * Update the specified Inscripcion in storage.
     *
     * @param int $id
     * @param UpdateInscripcionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateInscripcionRequest $request)
    {
        $inscripcion = $this->inscripcionRepository->find($id);

        if (empty($inscripcion)) {
            Flash::error('Inscripcion not found');

            return redirect(route('inscripcions.index'));
        }

        $inscripcion = $this->inscripcionRepository->update($request->all(), $id);

        Flash::success('Inscripcion updated successfully.');

        return redirect(route('inscripcions.index'));
    }

    /**
     * Remove the specified Inscripcion from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $inscripcion = $this->inscripcionRepository->find($id);

        if (empty($inscripcion)) {
            Flash::error('Inscripcion not found');

            return redirect(route('inscripcions.index'));
        }

        $this->inscripcionRepository->delete($id);

        Flash::success('Inscripcion deleted successfully.');

        return redirect(route('inscripcions.index'));
    }
}

resources/views/inscripcions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inscripcion
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'inscripcions.store']) !!}

                        @include('inscripcions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/inscripcions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inscripcion
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($inscripcion, ['route' => ['inscripcions.update', $inscripcion->id], 'method' => 'patch']) !!}

                        @include('inscripcions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/inscripcions/fields.blade.php
<div class="col-lg-12">
    <div class="form-group">
        <label for="form_lastname">Seleciona al Estudiante *</label>
        <select class="form-control select2-simple" name="estudiante_id" style="width: 100%;">
            @foreach($estudiantes  as $dato)
                <option value="{{$dato->id}}"  @if(!(Request::is('*inscripcions/create')) && ($reserva->estudiante_id==$dato->id))
                selected="selected"
                    @endif
                >
                    {{ $dato->registro }} - {{ $dato->persona->nombre }} {{ $dato->persona->apellido_paterno }} {{ $dato->persona->apellido_materno }}
                </option>
            @endforeach
        </select>
    </div>
</div>



<hr>
{{----------------------------------------------------------------------------------------}}
{{----------------------------------------------------------------------------------------}}
<div class="col-lg-12">
    <div class="form-group">
        <label for="form_lastname">Seleciona los Modulos *</label>
        <select class="form-control select2-multiple"  multiple="multiple" name="modulos_id[]" style="width: 100%;">
            @foreach($categoria  as $datosCategoria)
                @foreach($datosCategoria->programa  as $programa)
                    <optgroup label="  {{$datosCategoria->nombre }} | {{$programa->nombre }}">
                        @foreach($programa->Modulo  as $modulo)
                            <option value="{{$modulo->id}}">

                                {{ $modulo->id }}  - {{ $modulo->nombre }}   [ fecha inicio: {{ $modulo->fecha_inicio->format('Y-m-d') }} , Fecha fin:   {{ $modulo->fecha_fin->format('Y-m-d') }}] [ Hora Inicio: {{ $modulo->hora_inicio }}, Hora Salida {{ $modulo->hora_salida }})

                            </option>
                @endforeach
            @endforeach
            @endforeach
        </select>
    </div>
</div>
{{----------------------------------------------------------------------------------------}}


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('inscripcions.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/inscripcions/index.blade.php
@extends('layouts.app')
@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
@endsection
@section('content')
    <section class="content-header">
        <h1 class="pull-left">Inscripciones</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
               @can('inscripcions.create')
               href="{{ route('inscripcions.create') }}">Add New</a>
            @endcan
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        <br>
        {{ Form::open(['route' => 'inscripcions.index', 'method' => 'GET', 'class' => 'form-inline ']) }}
        <div class="form-group">
            {{ Form::text('codigo', $codigo, ['class' => 'form-control', 'placeholder' => 'Codigo']) }}
        </div>

        <div class="form-group">
            {{ Form::text('fecha', null, ['class' => 'form-control reportrange', 'placeholder' => 'fecha']) }}

            <div class="form-group">
                {{ Form::text('user', $user, ['class' => 'form-control', 'placeholder' => 'Usuario']) }}
            </div>

        </div>
        <div class="form-group">
            {{ Form::text('estudiante', $estudiante, ['class' => 'form-control', 'placeholder' => 'Estudiante']) }}
        </div>


        <div class="form-group">
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>Buscar
            </button>
        </div>
        {{ Form::close() }}
        <br>
        <div class="box box-primary">
            <div class="box-body">
                @include('inscripcions.table')
            </div>
        </div>
        <div class="text-center">

            @include('adminlte-templates::common.paginate', ['records' => $inscripciones])

        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script type="text/javascript">
    </script>
    <script type="text/javascript">
        $(function () {

            $('input[name="fecha"]').on('cancel.daterangepicker', function (ev, picker) {
                $(this).val('');
            });
            let start = moment().subtract(29, 'days');
            let end = moment();

            @if($fecha)

                start = @json( $fecha[0]);
            end = @json($fecha[1] );

            @endif
            console.log(start)


            $('.reportrange').daterangepicker({
                "locale": {
                    "format": "YYYY-MM-DD",
                    "separator": " to ",
                    "applyLabel": "Guardar",
                    "cancelLabel": "Cancelar",
                    "fromLabel": "Desde",
                    "toLabel": "Hasta",
                    "customRangeLabel": "Personalizar",
                    "daysOfWeek": [
                        "Do",
                        "Lu",
                        "Ma",
                        "Mi",
                        "Ju",
                        "Vi",
                        "Sa"
                    ],
                    "monthNames": [
                        "Enero",
                        "Febrero",
                        "Marzo",
                        "Abril",
                        "Mayo",
                        "Junio",
                        "Julio",
                        "Agosto",
                        "Setiembre",
                        "Octubre",
                        "Noviembre",
                        "Diciembre"
                    ],
                    // "firstDay": 1
                },
                startDate: start,
                endDate: end,
                alwaysShowCalendars: true,
                ranges: {
                    'Hoy': [moment(), moment()],
                    'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    '7 últimos días': [moment().subtract(6, 'days'), moment()],
                    '30 últimos días': [moment().subtract(29, 'days'), moment()],
                    'Este Mes': [moment().startOf('month'), moment().endOf('month')],
                    'El mes pasado': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                },
                //autoUpdateInput: false,
                //  autoUpdateInput: false,

            });


            //  cb("", "");

        });
    </script>
@endsection

resources/views/inscripcions/realizapago.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Pago
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')
    <div class="box box-primary">
        <div class="box-body">
            <div class="row">
            {!! Form::model($inscripcion, ['route' => ['pagar.inscripcion.post', $inscripcion->id], 'method' => 'put']) !!}
                <div class="form-group col-sm-12">
                <ul class="list-group">
                    <li class="list-group-item"><b>Codigo Estudiante:</b> {{ $inscripcion->Estudiante->registro }} </li>
                    <li class="list-group-item"><b>Carnet de Identidad: </b> {{ $inscripcion->Estudiante->Persona->ci}}  </li>
                    <li class="list-group-item"><b>Nombre: </b> {{ $inscripcion->Estudiante->Persona->nombre }} {{ $inscripcion->Estudiante->Persona->apellido_paterno }} {{ $inscripcion->Estudiante->Persona->apellido_materno }}</li>
                </ul>
                <hr>
                <h4>Modulos</h4>
                <ul class="list-group">
                    @foreach($inscripcion->modulos as $modulo)
                        <li class="list-group-item"><b> {{ $modulo->nombre }} - {{$modulo->costo}} /Bs.</b></li>
                    @endforeach
                </ul>
                <p>monto total : {{$inscripcion->modulos->sum('costo')}}</p>
                </div>
                <!-- Monto Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('monto', 'Monto:') !!}
                    {!! Form::text('monto', null, ['class' => 'form-control']) !!}
                </div>

                <!-- Nombre Field -->
                <div class="form-group col-sm-6">
                    {!! Form::label('nombre', 'Por concepto de:') !!}
                    {!! Form::text('nombre', null, ['class' => 'form-control']) !!}
                </div>

                <!-- Descripcion Field -->
                <div class="form-group col-sm-12 col-lg-12">
                    {!! Form::label('descripcion', 'Descripcion:') !!}
                    {!! Form::textarea('descripcion', null, ['class' => 'form-control']) !!}
                </div>

                <!-- Submit Field -->
                <div class="form-group col-sm-12">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                    <a href="{{ route('reservas.index') }}" class="btn btn-default">Cancel</a>
                </div>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/inscripcions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inscripcion
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('inscripcions.show_fields')
                    <a href="{{ route('inscripcions.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/inscripcions/show_fields.blade.php
<div class="form-group col-sm-12">

<h4>Datos De la Inscripcion</h4>

<ul class="list-group">
    <li class="list-group-item"><b>Codigo:</b> {{ $inscripcion->id}} </li>
    <li class="list-group-item"><b>Fecha: </b> {{$inscripcion->fecha}}  </li>
</ul>

    <h4>Datos Del Estudiante</h4>
<ul class="list-group">
    <li class="list-group-item"><b>Codigo Estudiante:</b> {{ $inscripcion->Estudiante->registro }} </li>
    <li class="list-group-item"><b>Carnet de Identidad: </b> {{ $inscripcion->Estudiante->Persona->ci}}  </li>
    <li class="list-group-item"><b>Nombre: </b> {{ $inscripcion->Estudiante->Persona->nombre }} {{ $inscripcion->Estudiante->Persona->apellido_paterno }} {{ $inscripcion->Estudiante->Persona->apellido_materno }}</li>
</ul>



    <h4>Modulos</h4>
    <ul class="list-group">
        @foreach($inscripcion->modulos as $modulo)
            <li class="list-group-item">
                <b> {{ $modulo->nombre }}  </b>
                <br>
                <small> [ fecha inicio: {{ $modulo->fecha_inicio->format('Y-m-d') }} , Fecha fin:   {{ $modulo->fecha_fin->format('Y-m-d') }}]
                    <br> [ Hora Inicio: {{ $modulo->hora_inicio }}, Hora Salida {{ $modulo->hora_salida }}]
                </small>
                <hr><b>Precio: {{$modulo->costo}} /Bs.</b>
            </li>
        @endforeach
    </ul>
</div>